location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    ingress:
      external: true
      targetPort: 8080
      transport: http
      allowInsecure: false
    registries:
    - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
      identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--postgresdb
        value: Host=pg;Port=5432;Username=postgres;Password={{ index .Inputs `pg` `password` }};Database=postgresdb
      - name: connectionstrings--servicebus
        value: '{{ .Env.SERVICEBUS_SERVICEBUSENDPOINT }}'
  template:
    containers:
    - image: {{ .Image }}
      name: producer
      env:
      - name: AZURE_CLIENT_ID
        value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
        value: "true"
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
        value: "true"
      - name: ConnectionStrings__postgresdb
        secretRef: connectionstrings--postgresdb
      - name: ConnectionStrings__serviceBus
        secretRef: connectionstrings--servicebus
    scale:
      minReplicas: 1
tags:
  azd-service-name: producer
  aspire-resource-name: producer
